import { iranSansX } from "@/lib/fonts";
import type { Metadata } from "next";
import "@/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={iranSansX.variable}>
      <body className={`font-iranSansX antialiased`}>{children}</body>
    </html>
  );
}
