import { iranSansX } from "@/lib/fonts";
import "@/styles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={iranSansX.variable}>
      <body className={`font-feature-farsi font-iranSansX antialiased`}>
        {children}
        <div id="popover-root"></div>
      </body>
    </html>
  );
}
